CREATE DATABASE IF NOT EXISTS TEST;
USE TEST;

CREATE TABLE PRODUCT_CATEGORY (
    ID INT NOT NULL PRIMARY KEY,
    NAME VARCHAR(35),
    DESCRIPTION TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);

CREATE TABLE PRODUCT_INVENTORY (
	ID INT NOT NULL PRIMARY KEY,
    QUANTITY INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODEFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);
CREATE TABLE DISCOUNT (
	ID INT NOT NULL PRIMARY KEY,
    NAME VARCHAR(25),
    DESCRIPTION TEXT,
    DISCOUNT_PERCENT DECIMAL,
    ACTIVE BOOLEAN,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);

CREATE TABLE PRODUCT (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(35),
    DESCRIPTION TEXT,
    SKU VARCHAR(25),
    CATEGORY_ID INT NOT NULL,
    INVENTORY_ID INT,
    PRICE DECIMAL,
    DISCOUNT_ID INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    MODEFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP,
    FOREIGN KEY (CATEGORY_ID)
		REFERENCES PRODUCT_CATEGORY(ID)
        ON DELETE CASCADE,
	FOREIGN KEY (INVENTORY_ID)
		REFERENCES PRODUCT_INVENTORY(ID)
        ON DELETE CASCADE,
	FOREIGN KEY (DISCOUNT_ID)
		REFERENCES DISCOUNT(ID)
		ON DELETE CASCADE
);